import { createHash } from "node:crypto";
import { readFile, stat, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { stripTones, toConcat } from "../src/pinyin.js";
import { type RawHskDataset, RawHskDatasetSchema } from "../src/schemas/rawHsk.js";

const DATASET_PATH = resolve(process.cwd(), "complete.json");
const OUTPUT_PATH = resolve(process.cwd(), "sql/seed.sql");

const FREQUENCY_SENTINEL_THRESHOLD = 100_000;

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlNullable(value: number | null): string {
  return value === null ? "NULL" : String(value);
}

function formKey(simplified: string, traditional: string, pinyin: string): string {
  return createHash("sha256")
    .update(`${simplified}|${traditional}|${pinyin}`)
    .digest("hex")
    .slice(0, 12);
}

function deriveLevels(levels: readonly string[]): {
  newLevel: number | null;
  oldLevel: number | null;
} {
  let newLevel: number | null = null;
  let oldLevel: number | null = null;
  for (const lv of levels) {
    if (lv.startsWith("new-")) {
      const n = Number(lv.slice(4));
      if (newLevel === null || n < newLevel) newLevel = n;
    } else if (lv.startsWith("old-")) {
      const n = Number(lv.slice(4));
      if (oldLevel === null || n < oldLevel) oldLevel = n;
    }
  }
  return { newLevel, oldLevel };
}

function buildFrequencyRanks(dataset: RawHskDataset): (number | null)[] {
  const eligible = dataset
    .map((entry, index) => ({ index, frequency: entry.frequency }))
    .filter((row) => row.frequency < FREQUENCY_SENTINEL_THRESHOLD);
  eligible.sort((a, b) => a.frequency - b.frequency);
  const ranks: (number | null)[] = new Array(dataset.length).fill(null);
  for (let r = 0; r < eligible.length; r++) {
    const row = eligible[r];
    if (row !== undefined) ranks[row.index] = r + 1;
  }
  return ranks;
}

type Buckets = {
  headwords: string[];
  forms: string[];
  glossFts: string[];
  pinyinFts: string[];
  hanziFts: string[];
};

function emit(dataset: RawHskDataset, ranks: (number | null)[]): Buckets {
  const buckets: Buckets = {
    headwords: [],
    forms: [],
    glossFts: [],
    pinyinFts: [],
    hanziFts: [],
  };

  let headwordId = 0;
  let formId = 0;

  for (const [i, entry] of dataset.entries()) {
    headwordId++;
    const rarity = entry.frequency >= FREQUENCY_SENTINEL_THRESHOLD ? "off_chart" : "common";
    const { newLevel, oldLevel } = deriveLevels(entry.level);
    const rank = ranks[i] ?? null;
    buckets.headwords.push(
      `INSERT INTO headwords (id, simplified, radical, frequency, frequency_rank, frequency_rarity, pos_tags, level_tags, new_level, old_level) VALUES (${headwordId}, ${sqlString(entry.simplified)}, ${sqlString(entry.radical)}, ${entry.frequency}, ${sqlNullable(rank)}, ${sqlString(rarity)}, ${sqlString(JSON.stringify(entry.pos))}, ${sqlString(JSON.stringify(entry.level))}, ${sqlNullable(newLevel)}, ${sqlNullable(oldLevel)});`,
    );

    for (const [j, form] of entry.forms.entries()) {
      formId++;
      const pinyin = form.transcriptions.pinyin;
      const pinyinPlain = stripTones(pinyin);
      const pinyinConcat = toConcat(pinyin);
      const key = formKey(entry.simplified, form.traditional, pinyin);
      const meaningsJson = JSON.stringify(form.meanings);
      const classifiersJson = JSON.stringify(form.classifiers);
      const glossEn = form.meanings.join("; ");
      const hanziConcat = entry.simplified + form.traditional;

      buckets.forms.push(
        `INSERT INTO forms (id, headword_id, form_index, form_key, traditional, pinyin, pinyin_plain, pinyin_concat, numeric, wadegiles, bopomofo, romatzyh, meanings_json, classifiers_json, gloss_en, hanzi_concat) VALUES (${formId}, ${headwordId}, ${j}, ${sqlString(key)}, ${sqlString(form.traditional)}, ${sqlString(pinyin)}, ${sqlString(pinyinPlain)}, ${sqlString(pinyinConcat)}, ${sqlString(form.transcriptions.numeric)}, ${sqlString(form.transcriptions.wadegiles)}, ${sqlString(form.transcriptions.bopomofo)}, ${sqlString(form.transcriptions.romatzyh)}, ${sqlString(meaningsJson)}, ${sqlString(classifiersJson)}, ${sqlString(glossEn)}, ${sqlString(hanziConcat)});`,
      );
      buckets.glossFts.push(
        `INSERT INTO gloss_fts (rowid, gloss_en) VALUES (${formId}, ${sqlString(glossEn)});`,
      );
      buckets.pinyinFts.push(
        `INSERT INTO pinyin_fts (rowid, pinyin_concat) VALUES (${formId}, ${sqlString(pinyinConcat)});`,
      );
      buckets.hanziFts.push(
        `INSERT INTO hanzi_fts (rowid, hanzi_concat) VALUES (${formId}, ${sqlString(hanziConcat)});`,
      );
    }
  }

  return buckets;
}

function assemble(buckets: Buckets): string {
  const lines: string[] = [
    "-- HSK MCP Server seed data",
    "-- Generated by scripts/build-seed.ts from complete.json.",
    "-- Re-run after `wrangler d1 execute DB --local --file=sql/schema.sql` to repopulate.",
    "-- Dataset pin: drkameleon/complete-hsk-vocabulary @ 7ac65bf1a6387d35f1ade478906172a19311c7f9",
    "",
    "BEGIN TRANSACTION;",
    "",
    "-- headwords",
    ...buckets.headwords,
    "",
    "-- forms",
    ...buckets.forms,
    "",
    "-- gloss_fts",
    ...buckets.glossFts,
    "",
    "-- pinyin_fts",
    ...buckets.pinyinFts,
    "",
    "-- hanzi_fts",
    ...buckets.hanziFts,
    "",
    "COMMIT;",
    "",
  ];
  return lines.join("\n");
}

async function main(): Promise<void> {
  const raw = await readFile(DATASET_PATH, "utf8");
  const dataset = RawHskDatasetSchema.parse(JSON.parse(raw));
  const ranks = buildFrequencyRanks(dataset);
  const buckets = emit(dataset, ranks);
  const sql = assemble(buckets);
  await writeFile(OUTPUT_PATH, sql, "utf8");
  const { size } = await stat(OUTPUT_PATH);
  console.log(`Wrote ${OUTPUT_PATH}`);
  console.log(`  headwords:  ${buckets.headwords.length.toLocaleString()}`);
  console.log(`  forms:      ${buckets.forms.length.toLocaleString()}`);
  console.log(`  fts rows:   ${buckets.glossFts.length.toLocaleString()} per index × 3`);
  console.log(`  bytes:      ${size.toLocaleString()}`);
}

await main();
